### ISSUE TITLE
Connections could not be acquired from the underlying database

### ISSUE THREAD

**Issue by samdai** [predix/rdpg-boshrelease#4]
Hello All,
I deployed rdpg-boshrelease to cloud foundry, creates a service instance and bind to application, when I execute command `cf env app1`, the connection params of postgres is as below:

```
  "postgres": [
   {
    "credentials": {
     "ID": 0,
     "binding_id": "326092ad-dc9f-41e9-95f4-3866533fb5d1",
     "dbname": "d58136656e65c4e25990a33a382c9e49e",
     "dsn": "host=10.244.2.16 port=5432 user=u58136656e65c4e25990a33a382c9e49e password=da771a3f83114c4a96dbd72371173505 dbname=d58136656e65c4e25990a33a382c9e49e connect_timeout=5 sslmode=disable",
     "hostname": "10.244.2.16",
     "instance_id": "6655272d-e928-4786-aed6-d23ecf2a8188",
     "jdbc_uri": "jdbc:postgre://u58136656e65c4e25990a33a382c9e49e:da771a3f83114c4a96dbd72371173505@10.244.2.16:5432/d58136656e65c4e25990a33a382c9e49e?sslmode=disable",
     "password": "da771a3f83114c4a96dbd72371173505",
     "port": "5432",
     "uri": "postgres://u58136656e65c4e25990a33a382c9e49e:da771a3f83114c4a96dbd72371173505@10.244.2.16:5432/d58136656e65c4e25990a33a382c9e49e?sslmode=disable",
     "username": "u58136656e65c4e25990a33a382c9e49e"
    },
    "label": "postgres",
    "name": "pg_intalio",
    "plan": "shared-nr",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "rdpg",
     "postgresql"
    ]
   }
  ]
```

I can use pgAdmin tool to connect to this database using the above connection params. but failed to get connection with code, the datasource configured in spring xml is as below:

```
    <bean id="datasource" class="com.mchange.v2.c3p0.ComboPooledDataSource"
        destroy-method="close">
        <!-- connection properties -->
        <property name="driverClass" value="org.postgresql.Driver" />
        <property name="jdbcUrl"
            value="#{'jdbc:postgresql://10.244.2.16:5432/d58136656e65c4e25990a33a382c9e49e'}" />
        <property name="user" value="u58136656e65c4e25990a33a382c9e49e" />
        <property name="password" value="da771a3f83114c4a96dbd72371173505" />

        <!-- pool size -->
        <property name="acquireIncrement" value="3" />
        <property name="initialPoolSize" value="5" />
        <property name="maxPoolSize" value="20" />
        <property name="minPoolSize" value="5" />

        <!-- trim old connections -->
        <property name="maxConnectionAge" value="300" /> <!-- 5 min -->
        <property name="maxIdleTime" value="180" /> <!-- 3 min -->
        <property name="maxIdleTimeExcessConnections" value="60" /> <!-- 1 min -->
        <property name="numHelperThreads" value="6" />

        <!-- test connections -->
        <property name="idleConnectionTestPeriod" value="300" /> <!-- 5 min -->
        <property name="testConnectionOnCheckin" value="true" />
        <property name="preferredTestQuery" value="SELECT 1" />

        <!-- disable prepared statement caching -->
        <property name="maxStatements" value="0" />
        <property name="maxStatementsPerConnection" value="0" />

        <!-- rollback uncommited changes on close -->
        <property name="autoCommitOnClose" value="false" />
    </bean>
```

The error thrown in backend is as below:

```
2016-07-05 02:31:49,057 ERROR [java.lang.Throwable] [ Thread-17] Exception in thread "Thread-17" org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
[Cause: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
    at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
    at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
    at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
    at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
    at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
    at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
    at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:391)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:471)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:481)
```

This datasource configuration and code works well when use other postgres service. Want to ask if there is sample that can work or I need configure something?

**Comment by samdai** [comment]
Has resolved this issue,  need add a security group to let rdpg vm can be accessed by cf container
